<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ubuntu" failures="0" tests="4" name="pBListener.SampleText" time="0.527" errors="1" timestamp="2023-07-03T13:40:34 IST" skipped="1">
  <testcase classname="pBListener.SampleText" name="TC3" time="0.000">
    <skipped/>
    <system-out>
      <![CDATA[This TC3 TC is skipped.....plz check dependent Method]]>
    </system-out>
  </testcase> <!-- TC3 -->
  <testcase classname="pBListener.SampleText" name="TC4" time="0.003">
    <system-out>
      <![CDATA[This TC4 exicution started....
TC4 is running...
This TC4 method completed successfully]]>
    </system-out>
  </testcase> <!-- TC4 -->
  <testcase classname="pBListener.SampleText" name="TC2" time="0.521">
    <error message="Method pBListener.SampleText.TC2() didn&#039;t finish within the time-out 500" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method pBListener.SampleText.TC2() didn't finish within the time-out 500
at java.base@17.0.7/java.lang.Thread.sleep(Native Method)
at app//pBListener.SampleText.TC2(SampleText.java:19)
at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
    <system-out>
      <![CDATA[This TC2 exicution started....
This TC2 method is fail plz try again]]>
    </system-out>
  </testcase> <!-- TC2 -->
  <testcase classname="pBListener.SampleText" name="TC1" time="0.003">
    <system-out>
      <![CDATA[This TC1 exicution started....
TC1 is running...
This TC1 method completed successfully]]>
    </system-out>
  </testcase> <!-- TC1 -->
  <system-out>
    <![CDATA[This TC2 exicution started....
This TC2 method is fail plz try again
This TC1 exicution started....
TC1 is running...
This TC1 method completed successfully
This TC4 exicution started....
TC4 is running...
This TC4 method completed successfully
This TC3 exicution started....
This TC3 TC is skipped.....plz check dependent Method]]>
  </system-out>
</testsuite> <!-- pBListener.SampleText -->
